services:

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev

  db:
    image: postgres:latest
    container_name: vegas-car-center-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      #Change this to any username
      POSTGRES_USER: postgres
      #Change this to any password (and keep it secure)
      POSTGRES_PASSWORD: postgres


